scrape_configs:

  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  - job_name: sample-prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets:
      - sample-webapi:80
      - sample-functions:80
