name: dotnet build and deploy sample services

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        required: false
        description: Azure resource group name
        type: string
      location:
        required: false
        description: Azure resource group location
        type: string
      deployment-mode:
        required: true
        description: Azure deployment mode
        type: choice
        options:
        - Complete
        - Incremental
        - Validate

  push:
    branches:
    paths:
    - .github/workflows/dotnet-webapp.yml
    - bicep/main-sample-service.bicep
    - src/**
  pull_request:
    branches: [ main ]

env:
  IS_MAIN_PUSH: ${{ github.ref == 'refs/heads/main' }}
  AZURE_RESOURCE_GROUP_NAME: ${{ github.event.inputs.resource-group-name || vars.RESOURCE_GROUP || format('{0}-sample-e2e', github.actor) }}
  AZURE_RESOURCE_GROUP_LOCATION: ${{ github.event.inputs.location || vars.LOCATION || 'centralus' }}
  AZURE_DEPLOYMENT_NAME: ${{ format('sample-e2e.{0}.{1}', github.actor, github.run_id) }}
  AZURE_DEPLOYMENT_MODE: >-
    ${{
      github.event.inputs.deployment-mode ||
      (github.ref == 'refs/heads/main' && 'Complete' || 'Validate')
    }}
  BUILD_CONFIGURATION: Release
  BICEP_TEMPLATE_PATH: ./bicep/main-sample-service.bicep
  DOTNET_VERSION: 6.0.x
  # These should be pulled from secrets, github will mask the output from being shown in logs
  ADDITIONAL_KEY_VAULT_SECRETS: >-
    {
      \"secrets\": [
          {\"name\": \"Sample--Secret\", \"secret\": \"Sample-Secret\" },
          {\"name\": \"Sample--Secret--Github\", \"secret\": \"${{ secrets.TEST_SECRET }}\" },
      ]
    }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --settings coverlet.runsettings.xml

    - name: Code Coverage
      run: |
        dotnet tool install --tool-path . dotnet-reportgenerator-globaltool
        mkdir code-coverage
        ./reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./code-coverage -reporttypes:"Cobertura;HtmlSummary"

    - name: Publish Code Coverage
      uses: actions/upload-artifact@v3
      with:
        name: sample-code-coverage
        path: ./code-coverage/

    - name: Publish WebApi
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      run: dotnet publish src/Sample.WebApi/Sample.WebApi.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output published/Sample.WebApi

    - name: Upload WebApi Build Artifact
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@v3
      with:
        name: Sample.WebApi
        path: published/Sample.WebApi

    - name: Publish Functions
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      run: dotnet publish src/Sample.Functions/Sample.Functions.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output published/Sample.Functions

    - name: Upload Functions Build Artifact
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@v3
      with:
        name: Sample.Functions
        path: published/Sample.Functions

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch')

    steps:
    - uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: packages

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set current Azure Subscription
      run: |
        #!/usr/bin/env bash

        set -euo pipefail

        az account show
        echo "AZURE_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)" >> $GITHUB_ENV
        echo "Logged in! 🎉"

    - name: Create Azure Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/usr/bin/env bash

          set -euo pipefail

          az group create --name $AZURE_RESOURCE_GROUP_NAME --location $AZURE_RESOURCE_GROUP_LOCATION

    - name: Deploy bicep 💪
      id: azure-deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        deploymentMode: ${{ env.AZURE_DEPLOYMENT_MODE }}
        deploymentName: ${{ env.AZURE_DEPLOYMENT_NAME }}
        template: ${{ env.BICEP_TEMPLATE_PATH }}
        failOnStdErr: false
        parameters: >-
          additionalSecrets="${{ env.ADDITIONAL_KEY_VAULT_SECRETS }}"
          developerObjectIdKeyVaultAccessPolicy="${{ secrets.AZURE_DEVELOPER_OBJECT_ID }}"

    - name: Deploy Sample.Functions
      uses: Azure/functions-action@v1
      if: success() && (env.AZURE_DEPLOYMENT_MODE != 'Validate')
      with:
        app-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}-functions
        package: packages/Sample.Functions

    - name: Sample.Function Health Check
      uses: Azure/CLI@v1
      if: success() && (env.AZURE_DEPLOYMENT_MODE != 'Validate')
      env:
        HOST_TO_TEST: ${{ steps.azure-deploy.outputs.functionsAppHealthCheckEndpoint }}
      with:
        inlineScript: |
          #!/usr/bin/env bash

          set -euxo pipefail

          # Find a better way to retry on transient errors
          echo "Delay..."
          sleep 60

          echo "Testing healthcheck..."
          curl $HOST_TO_TEST --retry 20 --retry-delay 10 --silent --fail --output /dev/null && true || false

          echo "Setting key..."
          # Force key creation in the key vault
          az functionapp function keys set \
            --resource-group "$AZURE_RESOURCE_GROUP_NAME" \
            --name "$AZURE_RESOURCE_GROUP_NAME-functions" \
            --function-name helloworldsecure \
            --key-name "default" > /dev/null

    - name: Deploy Sample.WebApi
      uses: azure/webapps-deploy@v2
      if: success() && (env.AZURE_DEPLOYMENT_MODE != 'Validate')
      with:
        app-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        package: packages/Sample.WebApi

    - name: Sample.WebApi Health Check
      uses: Azure/CLI@v1
      if: success() && (env.AZURE_DEPLOYMENT_MODE != 'Validate')
      env:
        HOST_TO_TEST: ${{ steps.azure-deploy.outputs.webAppHealthCheckEndpoint }}
      with:
        inlineScript: |
          #!/usr/bin/env bash
          set -euo pipefail

          echo "Testing healthcheck..."
          curl $HOST_TO_TEST --retry 20 --retry-delay 10 --silent --fail --output /dev/null && true || false

    - name: Save deployment Output
      env:
        AZURE_DEPLOY_OUTPUT: ${{ toJSON(steps.azure-deploy.outputs) }}
      run: |
        mkdir artifacts
        echo $AZURE_DEPLOY_OUTPUT
        echo $AZURE_DEPLOY_OUTPUT >> artifacts/deployment.json

    - name: Upload Azure Deploy Output
      uses: actions/upload-artifact@v3
      with:
        name: DeploymentOutput
        path: artifacts

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git
