name: test federated credentials

on:
  workflow_dispatch:
    inputs:
      environment-name:
        required: false
        description: GitHub 'environment' to deploy to
        type: string
  push:
    branches:
    - main

permissions:
  id-token: write

jobs:
  test-federated-credential:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment-name }}
    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Test Login
      run: |
        az ad sp list --display-name "${{ vars.SERVICE_PRINCIPAL_NAME }}" -o tsv --query '[].[id]'
